# Generated by Django 3.1.5 on 2021-03-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='blank', max_length=20, null=True)),
                ('name', models.CharField(default='blank', max_length=30, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(default='blank', max_length=12, null=True)),
                ('password', models.CharField(default='blank', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(default='blank', max_length=20, null=True)),
                ('recipient_email', models.EmailField(max_length=254, null=True)),
                ('recipient_mobile', models.CharField(default='blank', max_length=12, null=True)),
                ('item_type', models.CharField(default='blank', max_length=50, null=True)),
                ('item_name', models.CharField(default='blank', max_length=50, null=True)),
                ('item_weight', models.IntegerField(blank=True, null=True)),
                ('sender_pincode', models.CharField(max_length=12)),
                ('receiver_pincode', models.CharField(default='blank', max_length=50, null=True)),
                ('sender_address', models.TextField(default='blank', max_length=300, null=True)),
                ('receiver_address', models.TextField(default='blank', max_length=300, null=True)),
                ('package_images', models.ImageField(default='not_provided', null=True, upload_to='')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.user_info')),
            ],
        ),
    ]
