# Generated by Django 3.1.5 on 2021-03-18 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210316_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_requirement',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 11, 24, 59, 462075)),
        ),
        migrations.AlterField(
            model_name='client_requirement',
            name='package_images',
            field=models.ImageField(default='not_provided', null=True, upload_to='upload/orders'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
